"""product table

Revision ID: 10c14a102fd7
Revises: 
Create Date: 2021-06-13 16:51:00.937044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c14a102fd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year')
    op.drop_table('addpart')
    op.drop_table('model')
    op.drop_table('brand')
    op.drop_table('make')
    op.drop_table('user')
    op.drop_table('engine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=180), nullable=False),
    sa.Column('profile', sa.VARCHAR(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('profile')
    )
    op.create_table('make',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brand',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('addpart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('number', sa.VARCHAR(length=80), nullable=False),
    sa.Column('front_oenumber', sa.VARCHAR(length=80), nullable=False),
    sa.Column('rear_oenumber', sa.VARCHAR(length=80), nullable=False),
    sa.Column('sub_model', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('colors', sa.TEXT(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=False),
    sa.Column('make_id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('year_id', sa.INTEGER(), nullable=False),
    sa.Column('engine_id', sa.INTEGER(), nullable=False),
    sa.Column('image_1', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image_2', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image_3', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
